import { ORGANIZATION_NAME } from "@/shared/utils/constants";
import { sendMail } from "./transporter";
import {
  firstNameFrom,
  passwordResetEmailHtml,
  verificationEmailHtml,
  waitlistConfirmationHtml,
  welcomeEmailHtml,
} from "./templates";

export type VerificationEmailInput = {
  to: string;
  name: string;
  verifyUrl: string;
};

export type PasswordResetEmailInput = {
  to: string;
  name: string;
  resetUrl: string;
};

export type WelcomeEmailInput = {
  to: string;
  name: string;
  url: string;
};

export type WaitlistEmailInput = {
  to: string;
  name: string;
};

/** Low-level senders used by the email worker (and tests). */
export const sendEmailVerification = async ({
  to,
  name,
  verifyUrl,
}: VerificationEmailInput) => {
  await sendMail({
    to,
    subject: "Verify Your Email Address",
    html: verificationEmailHtml(firstNameFrom(name), verifyUrl),
  });
};

export const sendPasswordReset = async ({
  to,
  name,
  resetUrl,
}: PasswordResetEmailInput) => {
  await sendMail({
    to,
    subject: "Reset Your Password",
    html: passwordResetEmailHtml(firstNameFrom(name), resetUrl),
  });
};

export const sendWelcome = async ({ to, name, url }: WelcomeEmailInput) => {
  await sendMail({
    to,
    subject: `Welcome to ${ORGANIZATION_NAME}!`,
    html: welcomeEmailHtml(firstNameFrom(name), url),
  });
};

export const sendWaitlistConfirmation = async ({
  to,
  name,
}: WaitlistEmailInput) => {
  await sendMail({
    to,
    subject: "You've successfully joined the Waitlist!",
    html: waitlistConfirmationHtml(name),
  });
};

/** Invitation URLs are generated by the backend from the configured admin origin. */
export const sendModeratorInvitation = async (to: string, inviteUrl: string) => {
  const safeUrl = inviteUrl.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  await sendMail({
    to,
    subject: "You're invited to the Abio admin workspace",
    html: `<h1>Join the Abio team</h1><p>You have been invited to join the Abio workspace as a moderator.</p><p><a href="${safeUrl}">Accept invitation</a></p><p>This invitation expires in 7 days. Sign in with a verified account using the email address that received this invitation.</p><p>If you weren't expecting this invitation, you can ignore this email.</p>`,
  });
};
